version: '2'

services:
  web:
    depends_on:
      - 'mongo'
    build: .
    ports:
      - "8082:8082"
    links:
      - mongo
    tty: true
    stdin_open: true
    environment:
      - MONGO_CONN=mongodb://mongo:27017/edison

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo: